### ISSUE TITLE
Rebuild Nitro and rerun tests if deps change, e.g. routes

### ISSUE THREAD

**Issue by johannschopplich** [johannschopplich/nitro-test-utils#1]
Reported from @MickL in https://github.com/johannschopplich/nitro-starter/issues/1.

**Comment by MickL** [comment]
I absolutely appreciate that you've put in the time and effort to make this module! THANKS! Working on the frontend atm but will try it out as soon as I get back to the backend!

**Comment by johannschopplich** [comment]
Thanks for the feedback. 🙂 Glad to hear it's useful!
