### ISSUE TITLE
Enable Vite `envPrefix` for `NITRO_` in config by default

### ISSUE THREAD

**Issue by FrankiePo** [johannschopplich/nitro-test-utils#11]
It s strange that it is `nitro-test-utils`, but default prefix is `VITE_`
Otherwise `import.meta.env.NITRO_***` doesn't work

Currently working config for me is:

```ts
// vitest.config.mts

import { defineConfig } from 'nitro-test-utils/config';

export default defineConfig({
    nitro: {
        global: {
            // Set the root directory of your Nitro server
            rootDir: 'server',
        },
    },
    envPrefix: 'NITRO_',
});

```

**Comment by johannschopplich** [comment]
Hi there!
I get your point. Technically speaking, you're writing test files that will be transformed by Vite. To minimize the changes to a bare Vitest setup, I'd like to use the default of Vite.

Just like you did – if you prefer to support other environment prefixes, you can enable them via extending the Vitest config.
