### ISSUE TITLE
Tests failing with `AssertionError: expected 404 to be 200`

### ISSUE THREAD

**Issue by DesertCookie** [johannschopplich/nitro-test-utils#12]
I'm quite new with Nitro Test Utils. With the help of GPT-4o and the documentation and some examples from Stackoverflow, I got as far as attempting a simple test, yet always, no matter which of my endpoints I test, end up with a 404 error.

I created this endpoint in `server/api/health.get.ts` (found on Stackoverflow):

```ts
export default defineEventHandler(async (event) => {
	return {
		statusCode: 200,
		message: 'OK'
	}
})
```

I'm attempting to test it like so:

```ts
import { $fetchRaw, setup } from 'nitro-test-utils/e2e'
import { describe, expect, it } from 'vitest'
import { fileURLToPath } from "node:url";

describe('api', () => {
	it('responds successfully', async () => {
		const { data, status } = await $fetchRaw('/api/health')
		
		console.log('Response:', { data, status })
		
		expect(status).toBe(200)
		expect(data).toMatchSnapshot()
	})
})
```

`vitest.config.ts`:

```ts
import { defineConfig } from 'nitro-test-utils/config'

export default defineConfig({
	nitro: {
		global: true
	}
})
```

Having my dev server up and using Postman at `localhost:3000/api/health` returns `200 OK` and the data I sent back. It is only the tests that fail (run with `npx vitest`):

```
[success] [nitro] Nitro Server built in 550 ms
> Nitro Start (4ms)
> Nitro server running at http://localhost:3000/
stdout | tests/api/health.test.ts > api > responds successfully
Response: {
  data: {
    url: '/api/health',
    statusCode: 404,
    statusMessage: 'Cannot find any route matching /api/health.',
    message: 'Cannot find any route matching /api/health.'
  },
  status: 404
}

 ❯ tests/api/health.test.ts (1)
   ❯ api (1)
     × responds successfully

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯Failed Tests 1

 FAIL  tests/api/health.test.ts > api > responds successfully
AssertionError: expected 404 to be 200 // Object.is equality

- Expected
+ Received

- 200
+ 404

 ❯ tests/api/health.test.ts:11:18
      9|   console.log('Response:', { data, status })
     10|   
     11|   expect(status).toBe(200)
       |                  ^
     12|   expect(data).toMatchSnapshot()
     13|  })

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  1 failed (1)
```

Any help would be much appreciated.

**Comment by johannschopplich** [comment]
If you use Nitro without any custom Nitro environment, then you have to use the `api/health.get.ts` path instead of `server/api/health.get.ts`. Only if you set `srcDir` to `server` in your `nitro.config.ts` you can use this path.

Your code looks fine otherwise. Feel free to copy and paste the setup from the [test directory](https://github.com/johannschopplich/nitro-test-utils/tree/main/test/fixture).

**Comment by DesertCookie** [comment]
I do not quite understand how to accomplish what you said in global mode.

What is expected to work in my current situation? `$fetchRaw('/api/health')` does not work. You are not saying I should call `$fetchRaw('/api/health.get.ts')` either. What exactly should I call to reach the endpoint opened during the vitest run on `localhost:3000`?

**Comment by johannschopplich** [comment]
I'm sorry, but I don't have the resources to help you use this library. Your code looks fine. But I don't know your whole setup or Nitro server code. Make sure the Nitro config is in the same directory as the Vitest config.
As said earlier, I highly recommend you [check out the tests](https://github.com/johannschopplich/nitro-test-utils/blob/main/test/routes.test.ts) and start from there. 

If you encounter a bug, please provide a reproducible example and open a new issue. Thanks!

**Comment by DesertCookie** [comment]
Thank you for your time. I will create an Issue, if I narrow down the error.

So far, having pulled your repo here and only changing it to be a global setup, I get the same error I see in my project. At the same time, starting with a fresh Codesandbox, I don't experience this issue. If anything, this points at some issue on the two computers I tested with.
