### ISSUE TITLE
useStorage not working properly

### ISSUE THREAD

**Issue by YoungKamilson** [johannschopplich/nitro-test-utils#8]
### Problem description:
When using nitro-test-utils and trying to get something from Nitro JS storage I always get `null`.

```js
const code = await useStorage('assets:views').getItem(path);
const tailwindConfig = await useStorage('assets:views').getItem('mail/tailwindConfig.ts');
```

Both `code` and `tailwindConfig` are null.

The problem does not occur when running API in dev mode (`bun run dev`), without vitest enabled.
It happens only with `nitro-test-utils`

**vitest.config.mts**
```ts import { defineConfig } from 'nitro-test-utils/config';

export default defineConfig({
   nitro: {
      global: {
         rootDir: 'src',
         mode: 'development'
      }
   }
});
```

**Comment by johannschopplich** [comment]
Can you please provide a reproducible example and give more context where the storage is populated? Thanks!

**Comment by YoungKamilson** [comment]
Yes, of course. I use storage for serverAssets:

```ts
export default defineNitroConfig({
/////
serverAssets: [
      {
         baseName: 'views',
         dir: './views'
      }
   ],
/////
}
```
As simple as that.

**Comment by YoungKamilson** [comment]
No way, it was not working due to error in my vite config...
**rootDir** key was wrong
```ts
export default defineConfig({
   nitro: {
      global: {
      rootDir: 'src', //  ----> I removed this and now everything works :)
         mode: 'development'
      }
   }
});
```


Sorry for the confusion and thanks for help!
